const PERSONS_LIST_REQUEST="PERSONS_LIST_REQUEST";
const PERSONS_LIST_SUCCESS="PERSONS_LIST_SUCCESS";
const PERSONS_LIST_FAILURE="PERSONS_LIST_FAILURE";
const CREATE_PERSON_REQUEST="CREATE_PERSON_REQUEST";
const CREATE_PERSON_SUCCESS="CREATE_PERSON_SUCCESS";
const CREATE_PERSON_FAILURE="CREATE_PERSON_FAILURE";
const PERSON_DELETE_FAILURE="PERSON_DELETE_FAILURE";
const PERSON_DELETE_SUCCESS="PERSON_DELETE_SUCCESS";
const PERSON_DELETE_REQUEST="PERSON_DELETE_REQUEST";
const EDIT_PERSON_REQUEST="EDIT_PERSON_REQUEST";
const EDIT_PERSON_SUCCESS="EDIT_PERSON_SUCCESS";
const EDIT_PERSON_FAILURE="EDIT_PERSON_FAILURE";


const types = {
	PERSONS_LIST_REQUEST,
	PERSONS_LIST_SUCCESS,
	PERSONS_LIST_FAILURE,
	CREATE_PERSON_REQUEST,
	CREATE_PERSON_SUCCESS,
	CREATE_PERSON_FAILURE,
	PERSON_DELETE_FAILURE,
	PERSON_DELETE_SUCCESS,
	PERSON_DELETE_REQUEST ,
	EDIT_PERSON_REQUEST,
	EDIT_PERSON_SUCCESS,
	EDIT_PERSON_FAILURE	
}

export default types;