const MOVIES_LIST_REQUEST="MOVIES_LIST_REQUEST";
const MOVIES_LIST_SUCCESS="MOVIES_LIST_SUCCESS";
const MOVIES_LIST_FAILURE="MOVIES_LIST_FAILURE";
const CREATE_MOVIE_REQUEST="CREATE_MOVIE_REQUEST";
const CREATE_MOVIE_SUCCESS="CREATE_MOVIE_SUCCESS";
const CREATE_MOVIE_FAILURE="CREATE_MOVIE_FAILURE";
const MOVIE_DELETE_FAILURE="MOVIE_DELETE_FAILURE";
const MOVIE_DELETE_SUCCESS="MOVIE_DELETE_SUCCESS";
const MOVIE_DELETE_REQUEST="MOVIE_DELETE_REQUEST";
const EDIT_MOVIE_REQUEST="EDIT_MOVIE_REQUEST";
const EDIT_MOVIE_SUCCESS="EDIT_MOVIE_SUCCESS";
const EDIT_MOVIE_FAILURE="EDIT_MOVIE_FAILURE";
const UPDATE_DIRECTOR_REQUEST="UPDATE_DIRECTOR_REQUEST";
const UPDATE_DIRECTOR_SUCCESS="UPDATE_DIRECTOR_SUCCESS";
const UPDATE_DIRECTOR_FAILURE="UPDATE_DIRECTOR_FAILURE";


const types = {
	MOVIES_LIST_REQUEST,
 	MOVIES_LIST_SUCCESS,
 	MOVIES_LIST_FAILURE,
 	CREATE_MOVIE_REQUEST,
 	CREATE_MOVIE_SUCCESS,
 	CREATE_MOVIE_FAILURE,
 	MOVIE_DELETE_FAILURE,
 	MOVIE_DELETE_SUCCESS,
 	MOVIE_DELETE_REQUEST,
	EDIT_MOVIE_REQUEST,
	EDIT_MOVIE_SUCCESS,
	EDIT_MOVIE_FAILURE,	
	UPDATE_DIRECTOR_REQUEST,
	UPDATE_DIRECTOR_SUCCESS,
	UPDATE_DIRECTOR_FAILURE	
}

export default types